name: Generate Profile Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: MarceloRRMartins
          BRANCH_NAME: output
          UTC_OFFSET: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
